### ISSUE TITLE
Cannt find dataset

### ISSUE THREAD

**Issue by zy486at189cn** [ImagingLab/ICIAR2018#2]
First,it is a great job!
But ,the dataset web site is closed. I can not download the dataset. Can you send me some dataset?

**Comment by KamyarNazeri** [comment]
@zy486at189cn 
We cannot share the dataset with anyone according to the rules we have agreed on when we signed up for the challenge:

> The downloaded datasets or any data derived from these datasets, can not be given or redistributed under any circumstances to persons not belonging to the registered team.

Normally they release the dataset after the conference; you can access their 2015 dataset publically available at https://rdm.inesctec.pt/dataset/nis-2017-003
This dataset is smaller than 2018 challenge, however, images are with the same modality and the class scores are publically available!
